replicaCount: 2

image:
  registry: 024848487830.dkr.ecr.ap-south-1.amazonaws.com
  repository: demo-app
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
- name: ecr-secret

service:
  type: LoadBalancer
  port: 80

containerPort: 8080