name: Build and Dockerize

on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  build:
    env:
      AWS_REGION: "ap-south-1"
      AWS_ACCOUNT_ID: "024848487830"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup JAVA
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./sample-spring-app

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/demo-role

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Ensure ECR Repository Exists
      env:
        REPO_NAME: demo-app
      run: |
        if ! aws ecr describe-repositories --repository-names ${{ env.REPO_NAME }} --region ${{ env.AWS_REGION }}; then
          aws ecr create-repository --repository-name ${{ env.REPO_NAME }} --region ${{ env.AWS_REGION }}
        fi
        - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Docker image to Amazon ECR
      uses: docker/build-push-action@v6
      with:
        context: ./sample-spring-app
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:latest,${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ github.sha }}
        cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
        cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: demo-app
        IMAGE_TAG: ${{ github.sha }}