name: Deployment for demo-project
on:
  workflow_dispatch:
    inputs:
      terraform:
        description: 'Terrform actions to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  aws:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.terraform == 'plan' }} 
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Check Authentication
      run: aws sts get-caller-identity
